// This file was generated by RedwoodJS
import type { ComponentProps } from 'react'

import { Success } from './BlogpostCell'
import type { FindBlogpostQuery, FindBlogpostQueryVariables } from 'types/graphql'

type SuccessType = typeof Success

export * from './BlogpostCell'

type CellInputs = Omit<
  ComponentProps<SuccessType>,
  keyof QueryOperationResult | keyof FindBlogpostQuery | 'updating'
> & FindBlogpostQueryVariables

export default function (props: CellInputs): ReturnType<SuccessType>
