// This file was generated by RedwoodJS
import AboutPageType from '/home/ronaldo/Redwood/first_try_rw/web/src/pages/AboutPage/AboutPage'
import BlogPostPageType from '/home/ronaldo/Redwood/first_try_rw/web/src/pages/BlogPostPage/BlogPostPage'
import ContactPageType from '/home/ronaldo/Redwood/first_try_rw/web/src/pages/ContactPage/ContactPage'
import FatalErrorPageType from '/home/ronaldo/Redwood/first_try_rw/web/src/pages/FatalErrorPage/FatalErrorPage'
import HomePageType from '/home/ronaldo/Redwood/first_try_rw/web/src/pages/HomePage/HomePage'
import NotFoundPageType from '/home/ronaldo/Redwood/first_try_rw/web/src/pages/NotFoundPage/NotFoundPage'
import PostEditPostPageType from '/home/ronaldo/Redwood/first_try_rw/web/src/pages/Post/EditPostPage/EditPostPage'
import PostNewPostPageType from '/home/ronaldo/Redwood/first_try_rw/web/src/pages/Post/NewPostPage/NewPostPage'
import PostPostPageType from '/home/ronaldo/Redwood/first_try_rw/web/src/pages/Post/PostPage/PostPage'
import PostPostsPageType from '/home/ronaldo/Redwood/first_try_rw/web/src/pages/Post/PostsPage/PostsPage'

declare global {
  const AboutPage: typeof AboutPageType
  const BlogPostPage: typeof BlogPostPageType
  const ContactPage: typeof ContactPageType
  const FatalErrorPage: typeof FatalErrorPageType
  const HomePage: typeof HomePageType
  const NotFoundPage: typeof NotFoundPageType
  const PostEditPostPage: typeof PostEditPostPageType
  const PostNewPostPage: typeof PostNewPostPageType
  const PostPostPage: typeof PostPostPageType
  const PostPostsPage: typeof PostPostsPageType
}
