// This file was generated by RedwoodJS
import type { ComponentProps } from 'react'

import { Success } from './BlogpostsCell'
import type { BlogpostsQuery, BlogpostsQueryVariables } from 'types/graphql'

type SuccessType = typeof Success

export * from './BlogpostsCell'

type CellInputs = Omit<
  ComponentProps<SuccessType>,
  keyof QueryOperationResult | keyof BlogpostsQuery | 'updating'
> & BlogpostsQueryVariables

export default function (props: CellInputs): ReturnType<SuccessType>
